### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by ghost** [harmonizerblinks/loanapi#2]
Hi @harmonizerblinks,

Where can I find the frontend project is it opensource?

Could you also provide us with a demo account login credentials.

**Comment by harmonizerblinks** [comment]
@nicotravassos
https://dedawa-ea314.firebaseapp.com 
i have updated the readme file with these details

the Frontend isn't open source but source code can be provided at a fee.

**Comment by ghost** [comment]
Thanks @harmonizerblinks
